name: Azure Static Web Apps CI/CD - Gray Glacier

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Diagnostics (list dist contents)
        run: |
          echo "Dist directory listing:" || true
          ls -la dist || echo "dist not found" 
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Direct token for debugging - will replace with secret after success
          azure_static_web_apps_api_token: d64599a1567396afdb02f6e76eb2f9a09e383bfc2d3673c4c06c42fef37248e501-55e93f44-5ca0-4c0c-8609-19d843ed972500f0312039e6ef0f
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          api_location: ""
          output_location: "dist"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: d64599a1567396afdb02f6e76eb2f9a09e383bfc2d3673c4c06c42fef37248e501-55e93f44-5ca0-4c0c-8609-19d843ed972500f0312039e6ef0f
          action: "close"
